version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels: ["dependencies"]
    schedule:
      interval: "monthly"
    groups:
      go-deps:
        patterns:
          - "*"
    allow:
      - dependency-type: "direct"
    ignore:
      # Kubernetes deps are updated by fluxcd/pkg
      - dependency-name: "k8s.io/*"
      - dependency-name: "sigs.k8s.io/*"
      # Flux APIs are updated at release time
      - dependency-name: "github.com/fluxcd/image-reflector-controller/api"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: ["area/ci", "dependencies"]
    groups:
      ci:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
