name: fuzz
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  smoketest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: 1.25.x
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Smoke test Fuzzers
        run: make fuzz-smoketest
